version: '3.4'
services:

  jobmanager:
    image: flink:1.5.1-alpine
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - /tmp/flink-deployer:/data/flink

  taskmanager:
    image: flink:1.5.1-alpine
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - /tmp/flink-deployer:/data/flink

  echo-server:
    image: jmalloc/echo-server
    ports:
      - 8080

  deployer:
    build: .
    image: nielsdenissen/flink-deployer:master
    depends_on:
      - jobmanager
      - taskmanager
      - echo-server
    command: 
      - "deploy"
      - "--file-name"
      - "/tmp/flink-sample-job/flink-stateful-wordcount-assembly-0.jar"
      - "--entry-class"
      - "WordCountStateful"
      - "--parallelism"
      - "2"
      - "--jar-args"
      - "--intervalMs 1000"
    volumes:
      - /tmp/flink-deployer:/data/flink
      - ./flink-sample-job/target/scala-2.11/:/tmp/flink-sample-job
    environment:
      - FLINK_HOST=jobmanager
      - FLINK_PORT=8081
    links: 
      - jobmanager
      - echo-server